eclipse.preferences.version=1
org.eclipse.jdt.core.formatter.alignment_for_annotations_on_parameter=49
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_allocation_expression=48
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_explicit_constructor_call=48
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_method_invocation=48
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_qualified_allocation_expression=48
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_constructor_declaration=48
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration=48
org.eclipse.jdt.core.formatter.alignment_for_record_components=48
org.eclipse.jdt.core.formatter.alignment_for_selector_in_method_invocation=48
org.eclipse.jdt.core.formatter.blank_lines_after_imports=1
org.eclipse.jdt.core.formatter.blank_lines_after_package=1
org.eclipse.jdt.core.formatter.blank_lines_before_field=1
org.eclipse.jdt.core.formatter.blank_lines_before_method=1
org.eclipse.jdt.core.formatter.blank_lines_before_new_chunk=1
org.eclipse.jdt.core.formatter.continuation_indentation=1
org.eclipse.jdt.core.formatter.indentation.size=4
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_field=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_method=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_package=insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_parameter=do not insert
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_type=insert
org.eclipse.jdt.core.formatter.insert_space_after_comma_in_method_declaration_parameters=insert
org.eclipse.jdt.core.formatter.insert_space_around_assignment_operator=insert
org.eclipse.jdt.core.formatter.insert_space_around_binary_operator=insert
org.eclipse.jdt.core.formatter.keep_code_block_on_one_line=one_line_never
org.eclipse.jdt.core.formatter.keep_constructor_body_on_one_line=one_line_never
org.eclipse.jdt.core.formatter.keep_enum_constant_declaration_on_one_line=one_line_never
org.eclipse.jdt.core.formatter.keep_if_then_body_block_on_one_line=one_line_never
org.eclipse.jdt.core.formatter.keep_lambda_body_block_on_one_line=one_line_never
org.eclipse.jdt.core.formatter.keep_loop_body_block_on_one_line=one_line_never
org.eclipse.jdt.core.formatter.keep_method_body_on_one_line=one_line_never
org.eclipse.jdt.core.formatter.keep_switch_body_block_on_one_line=one_line_never
org.eclipse.jdt.core.formatter.join_wrapped_lines=false
org.eclipse.jdt.core.formatter.lineSplit=100
org.eclipse.jdt.core.formatter.number_of_empty_lines_to_preserve=1
org.eclipse.jdt.core.formatter.tabulation.char=space
org.eclipse.jdt.core.formatter.tabulation.size=4
org.eclipse.jdt.core.formatter.use_on_off_tags=false
